---
sudo: required
language: node_js
services: docker
node_js:
  - "10"
before_install:
  - "npm i -g npm@v6.0.1"
cache:
  -
    directories:
      - node_modules
install:
  - "npm install"

script:
  - "npm run test"
  - "npm run build"

after_success:
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ] && curl -H "Content-Type: application/json" --data "{\"build\": true}" -X POST $DOCKER_PUSH_URL'
